### ISSUE TITLE
Show grain boundary in Abaqus Output

### ISSUE THREAD

**Issue by lreigbua** [DylanAgius/Neper2Abaqus#1]
Thank you very much for this tool! It has been super useful.

Do you know of any way to show the grain boundaries in the Abaqus odb visualization? I can't find a way to show them with the results.

**Comment by lreigbua** [comment]
I was able to do it by creating a display group for each grain and adding them all together. Then, the feature edge will separate the grains.

**Comment by DylanAgius** [comment]
You’re very welcome! I’m pleased it has been helpful. Sorry for the late response but I’m glad you managed to find a way.
