### ISSUE TITLE
Error Neper2Abaqus

### ISSUE THREAD

**Issue by jdavidgg01** [DylanAgius/Neper2Abaqus#4]
Hi Dylan, i'm trying to run the example you have attached and is giving me this error in Matlab:
![image](https://user-images.githubusercontent.com/100253405/190287717-68070dba-e53b-426e-a24d-bc70dc82bc0a.png)

do you what is going on?
Thank you
Regards

David

**Comment by DylanAgius** [comment]
Hi David, so sorry for the late reply.  Have you managed to fix the issue?

Regards,

Dylan
